export class UIConfig {
    static DIMENSION_PADDING = 16
    static DIMENSION_CORNER = 8
    static DIMENSION_CIRCLE = 200
    static DIMENSION_PRESS_SHADOW = 6
    static DIMENSION_NORMAL_SHADOW = 12
    static DIMENSION_OFFSET_SHADOW = 12
    static FONT_LOGO = 48
    static FONT_HEADER = 36
    static FONT_TITLE = 24
    static FONT_SUB_TITLE = 20
    static FONT_CONTENT = 16
    static FONT_SUB_CONTENT = 12
    static FONT_BUTTON = 18

    static ANIM_DURATION = 200
}